name: dlipy3-wmlce162-cpu
channels:
- https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda
- defaults
dependencies:
- python==3.7.9
# WML-CE framework
- powerai-cpu==1.6.2
- keras==2.2.5
# WML-A dependencies
- nose==1.3.7
- requests==2.22.0
- pathlib==1.0.1
- redis-py==3.2.1
- chardet==3.0.4
- python-gflags==3.1.2
- pyzmq==17.1.2
- defusedxml==0.6.0
- ipython==7.13.0
- python-lmdb==0.94
- pandas==1.0.3
- gensim==3.8.0
- dill==0.3.1.1
