apiVersion: v1
kind: Pod
metadata:
   name: wmla-working-pod
spec:
      containers:
      - command:
        - sleep
        - "9999999"
        image: rhel7/rhel:latest
        name: ubi
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /gpfs
          name: mygpfs
        - mountPath: /var/shareDir
          name: persistsharedir
        - mountPath: /opt/anaconda3
          name: myconda
        - mountPath: /mylogging
          name: mylogging
      securityContext:
        runAsNonRoot: false
        privileged: true
        runAsUser: 0
      serviceAccount: wmla-sa
      serviceAccountName: wmla-sa
      volumes:
      - name: mygpfs
        persistentVolumeClaim:
          claimName: wmla-mygpfs
      - name: persistsharedir
        persistentVolumeClaim:
          claimName: wmla-cws-share
      - name: myconda
        persistentVolumeClaim:
          claimName: wmla-conda
      - name: mylogging
        persistentVolumeClaim:
          claimName: wmla-logging
