name: dlinsights
channels:
- defaults
dependencies:
- python==3.7.9
- pip
- numpy==1.18.1
- scipy==1.3.0
- pyopenssl==18.0.0
- pathlib==1.0.1
- requests==2.23.0
- sqlalchemy==1.3.13
- flask==1.0.3
- flask-cors==3.0.8
- pip:
   # not avaliable in conda
   - alembic==1.2.1
   - elasticsearch==7.1.0
   - mongoengine==0.15.0
   - flask-script==2.0.6   
   - flask-httpauth==3.3.0